
version: '3'

services:
  postgres-db:
    image: cat_project:3.0
    build:
      ./docker
    volumes:
      - ./postgres-db/pgdata/pgdata

    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - PGDATA=/pgdata
      - POSTGRES_DB=test_db
    ports:
      - "5432:5432"
    # mem_limit: 512m
    # restart: always
    # command: ["postgres", "-c", "log_statement=all"]

  # testredis:
  #   image: redis:latest
  #   ports:
  #     - '6379:6379'
  #   mem_limit: 128m
  #   restart: always
