[database]
    host="localhost"
    port=5432
    user="admin_local"
    password="root"
    db_name="zerofour"

[api]
    url="localhost:8888"

[redis]
    address="localhost:6379"
    password=""
    db="steven"

[token_auth]
    expire = 28800 # in seconds

