[database]
    host="localhost"
    port=5432
    user="project_steven"
    password="secrect"
    db_name="project_steven"

[api]
    url="localhost:8080"

[redis]
    address="localhost:6379"
    password=""
    db=""

[token_auth]
    expire = 28800 # in seconds