[database]
    host="localhost"
    port=5432
    user="myuser"
    password="mypassword"
    db_name="mydatabase"

[api]
    url="localhost:8888"

[redis]
    address="localhost:6379"
    password=""
    db=""

[token_auth]
    expire = 28800 # in seconds